### ISSUE TITLE
Any tip to make @apply work?

### ISSUE THREAD

**Issue by kvetoslavnovak** [fergusfrl/svelte-tailwind-snowpack#1]
First of all big thank you for this repo and great blog post!
 Do you have any tip how to make Tailwind @applydirective to work in Svelte/Sapper?

**Comment by fergusfrl** [comment]
I'm glad the article was helpful 🙂 
I haven't used Sapper so I'm really not in the best position to help you I'm afraid. Check out this article by CodeChips about integrating Tailwind CSS with Sapper: https://codechips.me/sapper-with-postcss-and-tailwind/
